SAHAM_LIST = [
 
    "KIOS", "KJEN", "KKGI", "KLAS", "KLBF", "KLIN", "KMDS", "KMTR", "KOBX", "KOCI", 
    "KOKA", "KONI", "KOPI", "KOTA", "KPIG", "KRAS", "KRYA", "KSIX", "KUAS", "LABA", 
    "LABS", "LAJU", "LAND", "LAPD", "LCKM", "LEAD", "LFLO", "LIFE", "LINK", "LION", 
    "LIVE", "LMAX", "LMPI", "LOPI", "LPCK", "LPGI", "LPIN", "LPKR", "LPLI", "LPPF", 
    "LPPS", "LRNA", "LSIP", "LTLS", "LUCK", "LUCY", "MAHA", "MAIN", "MANG", "MAPA", 
    "MAPB", "MAPI", "MARK", "MASB", "MAXI", "MAYA", "MBAP", "MBMA", "MBSS", "MBTO", 
    "MCAS", "MCOL", "MCOR", "MDIA", "MDIY", "MDKA", "MDKI", "MDLA", "MDLN", "MEDC", 
    "MEDS", "MEGA", "MEJA", "MERI", "MERK", "META", "MGLV", "MGNA", "MGRO", "MHKI", 
    "MICE", "MIDI", "MIKA", "MINA", "MINE", "MITI", "MKAP", "MKPI", "MKTR", "MLBI", 
    "MLIA", "MLPL", "MLPT", "MMIX", "MMLP", "MNCN", "MOLI", "MORA", "MPIX", "MPMX", 
    "MPOW", "MPRO", "MPXL", "MRAT", "MREI", "MSIE", "MSIN", "MSJA", "MSKY", "MSTI", 
    "MTDL", "MTEL", "MTLA", "MTMH", "MTWI", "MUTU", "MYOH", "MYOR", "NAIK", "NANO", 
    "NASI", "NATO", "NAYZ", "NCKL", "NELY", "NEST", "NETV", "NFCX", "NICE", "NICK", 
    "NICL", "NIKL", "NINE", "NIRO", "NISP", "NOBU", "NPGF", "NRCA", "NSSS", "NTBK", 
    "NZIA", "OASA", "OBAT", "OBMD", "OILS", "OKAS", "OLIV", "OMED", "OPMS", "PACK", 
    "PADA", "PADI", "PALM", "PAMG", "PANI", "PANR", "PANS", "PART", "PBID", "PBSA", 
    "PDES", "PDPP", "PEGE", "PEHA", "PEVE", "PGAS", "PGEO", "PGLI", "PGUN", "PICO", 
    "PIPA", "PJAA", "PJHB", "PKPK", "PLAN", "PMJS", "PMUI", "PNBN", "PNBS", "PNGO", 
    "PNIN", "PNLF", "PNSE", "POLA", "POLI", "POLU", "PORT", "POWR", "PPGL", "PPRE", 
    "PPRI", "PRAY", "PRDA", "PRIM", "PSAB", "PSAT", "PSDN", "PSGO", "PSKT", "PSSI", 
    "PTBA", "PTIS", "PTMP", "PTPP", "PTPS", "PTPW", "PTRO", "PTSN", "PTSP", "PUDP", 
    "PURI", "PWON", "PYFA", "PZZA", "RAAM", "RAJA", "RALS", "RANC", "RATU", "RCCC", 
    "RDTX", "REAL", "RELF", "RELI", "RGAS", "RICY", "RIGS", "RISE", "RLCO", "RMKE", 
    "RMKO", "ROCK", "RODA", "RONY", "ROTI", "RSCH", "RUIS", "RUNS", "SAFE", "SAME", 
    "SAMF", "SAPX", "SATU", "SBMA", "SCCO", "SCMA", "SCNP", "SDMU", "SDPC", "SDRA", 
    "SEMA", "SFAN", "SGER", "SGRO", "SHID", "SHIP", "SICO", "SIDO", "SILO", "SIMP", 
    "SIPD", "SKBM", "SKLT", "SKRN", "SLIS", "SMAR", "SMBR", "SMDM", "SMDR", "SMGA", 
    "SMGR", "SMIL", "SMKL", "SMKM", "SMLE", "SMMA", "SMMT", "SMRA", "SMSM", "SNLK", 
    "SOCI", "SOFA", "SOHO", "SOLA", "SONA", "SOTS", "SOUL", "SPMA", "SPRE", "SPTO", 
    "SRAJ", "SRSN", "SRTG", "SSIA", "SSMS", "SSTM", "STAA", "STAR", "STRK", "STTP", 
    "SULI", "SUNI", "SUPA", "SURE", "SURI", "SWID", "TALF", "TAPG", "TAYS", "TBIG", 
    "TBLA", "TBMS", "TCID", "TCPI", "TEBE", "TFAS", "TGKA", "TIFA", "TINS", "TIRA", 
    "TKIM", "TLDN", "TLKM", "TMAS", "TMPO", "TNCA", "TOBA", "TOOL", "TOSK", "TOTL", 
    "TOTO", "TOWR", "TPIA", "TPMA", "TRGU", "TRIM", "TRIN", "TRIS", "TRJA", "TRON", 
    "TRST", "TRUE", "TRUK", "TRUS", "TSPC", "TUGU", "TYRE", "UANG", "UCID", "UFOE", 
    "ULTJ", "UNIC", "UNIQ", "UNIT", "UNTD", "UNTR", "UNVR", "URBN", "UVCR", "VAST", 
    "VERN", "VICI", "VICO", "VINS", "VISI", "VKTR", "VOKS", "VRNA", "VTNY", "WAPO", 
    "WBSA", "WEGE", "WEHA", "WGSH", "WIDI", "WIFI", "WIIM", "WINE", "WINS", "WIRG", 
    "WMUU", "WOMF", "WOOD", "WOWS", "WTON", "YELO", "YOII", "YPAS", "YULE", "YUPI", 
    "ZATA", "ZONE", "ZYRX", "JKSE"
]
